#spring:
#  application:
#    name: data-multidatasource
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://103.50.253.167:3306/test?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 941108
#  second-datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://103.50.253.167:3306/db2?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 941108
server:
  port: 8888
mybatis:
  config-location: classpath:mybatis_config.xml
logging:
  config: classpath:logback.xml
hello:
  msg: world

spring:
  datasource:
    test1:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://103.50.253.167:3306/test?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 941108
    test2:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://103.50.253.167:3306/db1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 941108
  redis:
    host: 103.50.253.167
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false